networks:
  racing_net:
    driver: bridge

services:
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile_scrapper
    volumes:
      - /:/home/jovyan/
    restart: always
    depends_on:
      - postgres
    networks:
      - racing_net

  webapp:
    build:
      context: .
      dockerfile: Dockerfile_webapp
    volumes:
      - /:/home/jovyan/
    ports:
      - "8080:5001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - racing_net

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: racing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - racing_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
