FROM python:3.11
USER root

RUN mkdir -p /code
WORKDIR /code/web_app

RUN apt-get update

COPY ./web_app/poetry.lock ./web_app/pyproject.toml /code/web_app/

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . /code
EXPOSE 5000
ENTRYPOINT [ "python" ]
CMD ["app.py"]
