# FROM selenium/standalone-chrome

# USER root
# RUN wget https://bootstrap.pypa.io/get-pip.py
# RUN python3 get-pip.py
# RUN python3 -m pip install selenium


FROM joyzoursky/python-chromedriver:3.9-selenium

RUN mkdir packages
ADD requirements.txt packages
RUN pip install -r packages/requirements.txt

RUN mkdir -p /code
WORKDIR /code/scrapper

RUN apt-get update
# RUN apt-get install python3-pip

# COPY ./scrapper/poetry.lock ./scrapper/pyproject.toml /code/scrapper/
# COPY requirements.txt /code/

# RUN pip install -r requirements.txt

# RUN curl -sSL https://install.python-poetry.org | python3 -
# ENV PATH="/root/.local/bin:$PATH"
# RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . /code
CMD ["tail", "-f", "/dev/null"]
# ENTRYPOINT [ "poetry", "run", "python" ]
# CMD ["run_full_scrap.py"]
