services:
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile_scrapper
    volumes:
      - /:/home/jovyan/
    restart: always
    depends_on:
      - postgres

  webapp:
    build:
      context: .
      dockerfile: Dockerfile_webapp
    volumes:
      - /:/home/jovyan/
    ports:
      - "8080:5001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: racing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
