# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables to prevent prompts from Chrome
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages including Chrome and Selenium dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    curl \
    gnupg \
    libnss3 \
    libgconf-2-4 \
    libxss1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libx11-xcb1 \
    libgbm-dev \
    libpangocairo-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Install Chromium directly
RUN apt-get update && apt-get install -y chromium \
    && rm -rf /var/lib/apt/lists/*

# Set the display environment variable to allow headless operation
ENV DISPLAY=:99

# Set working directory
WORKDIR /app/scrapper

# Copy your project files
COPY . /app

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install -r requirements.txt
    
# Make sure the script is executable
RUN chmod +x run_full_scrap.py

# Command to run the scraping script
CMD ["python", "./run_full_scrap.py"]
