FROM selenium/standalone-chrome

USER root
RUN apt-get update

RUN mkdir -p /code
WORKDIR /code/scrapper

COPY ./scrapper/poetry.lock ./scrapper/pyproject.toml /code/scrapper/

RUN curl -sSL https://install.python-poetry.org | python3 - && \
    export PATH="/root/.local/bin:$PATH"

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY . /code
ENTRYPOINT [ "poetry", "run", "python" ]
CMD ["run_full_scrap.py"]
