services:
    
  scrapper:
      build:
        context: ./scrapper
        dockerfile: Dockerfile
      volumes:
        - scrapper/:/home/jovyan/scrapper/

  webapp:
      build:
        context: .
        dockerfile: Dockerfile_webapp
      volumes:
        - web_app/:/home/jovyan/web_app/

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      