tracks_to_types = {
    "Atlanta Motor Speedway": "Intermediate",
    "Auto Club Speedway": "Intermediate",
    "Bristol Motor Speedway": "Short Track",
    "Canadian Tire Motorsport Park": "Road Course",
    "Charlotte Motor Speedway": "Intermediate",	
    "Charlotte Motor Speedway Road Course": "Road Course",
    "Chicago Street Course": "Road Course",
    "Chicagoland Speedway":	 "Intermediate",
    "Circuit of the Americas": "Road Course",
    "Daytona Road Course": "Road Course",
    "Darlington Raceway": "Intermediate",
    "Daytona International Speedway": "Superspeedway",
    "Dover Motor Speedway": "Intermediate",
    "Eldora Speedway": "Short Track",
    "Homestead-Miami Speedway": "Intermediate",
    "Indianapolis Motor Speedway": "Intermediate",
    "Indianapolis Motor Speedway Road Course": "Road Course",
    "Iowa Speedway": "Short Track",
    "Kansas Speedway": "Intermediate",
    "Kentucky Speedway": "Intermediate",
    "Knoxville Raceway": "Short Track",
    "Las Vegas Motor Speedway": "Intermediate",
    "Los Angeles Memorial Coliseum": "Short Track",
    "Lucas Oil Indianapolis Raceway": "Short Track",
    "Martinsville Speedway": "Short Track",
    "Michigan International Speedway": "Intermediate",
    "Mid-Ohio Sports Car Course": "Road Course",
    "Milwaukee Mile Speedway": "Short Track",
    "Nashville Superspeedway": "Intermediate",
    "New Hampshire Motor Speedway": "Intermediate",
    "North Wilkesboro Speedway": "Short Track",
    "Phoenix Raceway": "Intermediate",
    "Pocono Raceway": "Intermediate",
    "Portland International Raceway": "Road Course",
    "Richmond Raceway": "Short Track",
    "Road America": "Road Course",
    "Sebring Raceway": "Road Course",
    "Sonoma Raceway": "Road Course",
    "Talladega Superspeedway": "Superspeedway",
    "Texas Motor Speedway": "Intermediate",
    "Watkins Glen International": "Road Course",
    "World Wide Technology Raceway at Gateway": "Intermediate",
}

tracks_to_short = {
    "Atlanta Motor Speedway": "Atlanta",
    "Auto Club Speedway": "Auto Club",
    "Bristol Motor Speedway": "Bristol",
    "Canadian Tire Motorsport Park": "Canadian Tire",
    "Charlotte Motor Speedway": "Charlotte",	
    "Charlotte Motor Speedway Road Course": "Charlotte Road Course",
    "Chicago Street Course": "Chicago",
    "Chicagoland Speedway":	 "Chicagoland",
    "Circuit of the Americas": "COTA",
    "Daytona Road Course": "Daytona Road Course",
    "Darlington Raceway": "Darlington",
    "Daytona International Speedway": "Daytona",
    "Dover Motor Speedway": "Dover",
    "Eldora Speedway": "Eldora",
    "Homestead-Miami Speedway": "Homestead-Miami",
    "Indianapolis Motor Speedway": "Indianapolis",
    "Indianapolis Motor Speedway Road Course": "Indianapolis Road Course",
    "Iowa Speedway": "Iowa",
    "Kansas Speedway": "Kansas",
    "Kentucky Speedway": "Kentucky",
    "Knoxville Raceway": "Knoxville",
    "Las Vegas Motor Speedway": "Las Vegas",
    "Los Angeles Memorial Coliseum": "Los Angeles",
    "Lucas Oil Indianapolis Raceway": "Lucas Oil Indianapolis",
    "Martinsville Speedway": "Martinsville",
    "Michigan International Speedway": "Michigan",
    "Mid-Ohio Sports Car Course": "Mid-Ohio",
    "Milwaukee Mile Speedway": "Milwaukee",
    "Nashville Superspeedway": "Nashville",
    "New Hampshire Motor Speedway": "New Hampshire",
    "North Wilkesboro Speedway": "North Wilkesboro",
    "Phoenix Raceway": "Phoenix",
    "Pocono Raceway": "Pocono",
    "Portland International Raceway": "Portland",
    "Richmond Raceway": "Richmond",
    "Road America": "Road America",
    "Sebring Raceway": "Sebring",
    "Sonoma Raceway": "Sonoma",
    "Talladega Superspeedway": "Talladega",
    "Texas Motor Speedway": "Texas",
    "Watkins Glen International": "Watkins Glen",
    "World Wide Technology Raceway at Gateway": "Gateway",
}